language: csharp
solution: ./FDV.BikesRent.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore ./FDV.BikesRent.sln

script:
  - xbuild ./FDV.BikesRent.sln
  - nunit-console ./FDV.BikesRent.Test/bin/Debug/FDV.BikesRent.Test.dll
